# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Broc Klein : Literary Agent'
email: hjeebus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Representing the Best of the Best
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hjeebus.com" # the base hostname & protocol for your site
twitter_username: hjeebus
github_username: hjeebus

# Build settings
markdown: kramdown
gems:
  - bourbon
  - neat
